name: CI/CD - Staging

on:
  push:
    branches:
      - release/**

  pull_request:
    branches:
      - release/**
jobs:
  run-tests:
    uses: ./.github/workflows/template-tests.yml
    with:
      node-version: "18"

  build-and-deploy:
    name: Construir y Desplegar (Staging)
    runs-on: ubuntu-latest
    needs: run-tests

    env:
      IMAGE_NAME: craftica-backend
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      REF_NAME: ${{ github.ref_name }}
      SHORT_SHA: ${{ github.sha }}

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar pruebas
        run: npm test

      - name: Construir imagen Docker
        run: docker build -t $IMAGE_NAME:latest .

      - name: Autenticarse en DockerHub
        run: echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - name: Subir imagen a DockerHub
        run: |
          docker tag $IMAGE_NAME:latest $DOCKERHUB_USERNAME/$IMAGE_NAME:staging-${REF_NAME}
          docker tag $IMAGE_NAME:latest $DOCKERHUB_USERNAME/$IMAGE_NAME:staging-${SHORT_SHA::7}
          docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:staging-${REF_NAME}
          docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:staging-${SHORT_SHA::7}
