name: CI - Craftica

on:
  push:
    branches:
      - develop
      - feature/**

  pull_request:
    branches:
      - develop
      - feature/**
jobs:
  test:
    uses: ./.github/workflows/template-tests.yml
    with:
      node-version: "18"
