name: Reusable Tests - Craftica

on:
  workflow_call:
    inputs:
      node-version:
        description: "Node.js version to use"
        required: false
        default: "18"
        type: string

jobs:
  run-tests:
    name: Ejecutar pruebas
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version}}

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar pruebas
        run: npm test
